### ISSUE TITLE
OrderedSet.index(...) function throws error when key is a frozenset

### ISSUE THREAD

**Issue by KSneijders** [rspeer/ordered-set#95]
I'm unable to use `OrderedSet.index(...)` function with `frozenset`s as values. It throws an error when the key is a frozenset.

Code to recreate the error:

```py
os = OrderedSet([frozenset([1, 2])])
i = os.index(frozenset([1, 2]))
```

```py
Traceback (most recent call last):
  File "<PATH>\src\main.py", line 11, in <module>
    i = os.index(frozenset([1, 2]))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<PATH>\Python311\Lib\site-packages\ordered_set\__init__.py", line 246, in index
    return [self.index(subkey) for subkey in key]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<PATH>\Python\Python311\Lib\site-packages\ordered_set\__init__.py", line 246, in <listcomp>
    return [self.index(subkey) for subkey in key]
            ^^^^^^^^^^^^^^^^^^
  File "<PATH>\Python\Python311\Lib\site-packages\ordered_set\__init__.py", line 247, in index
    return self.map[key]
           ~~~~~~~~^^^^^
KeyError: 1
```

Thanks for this amazing utility!

**Comment by KSneijders** [comment]
@rspeer Hey, sorry for the ping- is this package still in 'active' development? 🙂
